/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.omega;

import com.mycompany.omega.LoginFrame;
import com.mycompany.omega.classes.Admin;
import com.mycompany.omega.classes.Session;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author Lee Anwen
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    private Admin admin;
    public AdminFrame() {
        initComponents();
        admin = (Admin) Session.getCurrentUser();
        LabelWelcome.setText("Welcome, " + admin.getRole() + ": " + admin.getName());
        btnRegisterUsers.setVisible(false);
        btnDeleteUsers.setVisible(false);
        btnViewUsers.setVisible(false);
        btnRegister.setVisible(false);
        lblEmail.setVisible(false);
        lblEmployeeID.setVisible(false);
        lblName.setVisible(false);
        lblPassword.setVisible(false);
        lblRole.setVisible(false);
        txtEmail.setVisible(false);
        txtEmployeeID.setVisible(false);
        txtName.setVisible(false);
        txtPassword.setVisible(false);
        boxRole.setVisible(false);
        btnReturn.setVisible(false);
        tblUsers.setVisible(false);
        btnReturn2.setVisible(false);
        lblDeleteEmployee.setVisible(false);
        btnDelete.setVisible(false);
        txtDeleteEmployeeID.setVisible(false);
        btnReturn3.setVisible(false);
        jScrollPane2.setVisible(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelWelcome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnManageUsers = new javax.swing.JButton();
        btnManageItems = new javax.swing.JButton();
        btnManageSupplier = new javax.swing.JButton();
        btnViewEditPR = new javax.swing.JButton();
        btnViewEditPO = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnRegisterUsers = new javax.swing.JButton();
        btnDeleteUsers = new javax.swing.JButton();
        btnViewUsers = new javax.swing.JButton();
        lblEmployeeID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        boxRole = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblDeleteEmployee = new javax.swing.JLabel();
        txtDeleteEmployeeID = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnReturn3 = new javax.swing.JButton();
        btnReturn2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        LabelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LabelWelcome.setText("Welcome, ");

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 821, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(LabelWelcome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });

        btnManageItems.setText("Manage Items");
        btnManageItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageItemsActionPerformed(evt);
            }
        });

        btnManageSupplier.setText("Manage Suppliers");

        btnViewEditPR.setText("View/Edit PurchaseRequisition");
        btnViewEditPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditPRActionPerformed(evt);
            }
        });

        btnViewEditPO.setText("View/Edit PurchaseOrder");
        btnViewEditPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEditPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewEditPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewEditPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageItems, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewEditPR, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewEditPO, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegisterUsers.setText("Register Users");
        btnRegisterUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUsersActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegisterUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 54, 143, 71));

        btnDeleteUsers.setText("Delete Users");
        btnDeleteUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUsersActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 54, 143, 71));

        btnViewUsers.setText("View Users");
        btnViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUsersActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 54, 143, 71));

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployeeID.setText("EmployeeID");
        lblEmployeeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 177, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setText("Name");
        lblName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 222, 104, -1));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole.setText("Role");
        lblRole.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 267, 104, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 312, 104, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 357, 104, -1));
        jPanel3.add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 177, 350, -1));
        jPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 227, 350, -1));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 312, 350, -1));
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 362, 350, -1));

        boxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRATOR", "SALES_MANAGER", "PURCHASE_MANAGER", "FINANCE_MANAGER", "INVENTORY_MANAGER", " " }));
        boxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRoleActionPerformed(evt);
            }
        });
        jPanel3.add(boxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 267, -1, -1));

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 428, 123, 39));

        btnReturn.setText("RETURN");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 428, 123, 39));

        lblDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDeleteEmployee.setText("Enter EmployeeID to Delete:");
        lblDeleteEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblDeleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        jPanel3.add(txtDeleteEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 220, 30));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, 40));

        btnReturn3.setText("RETURN");
        btnReturn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 40));

        btnReturn2.setText("RETURN");
        btnReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 130, 40));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUsers);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 560, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageItemsActionPerformed

    private void btnViewEditPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewEditPRActionPerformed

    private void btnViewEditPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewEditPOActionPerformed

    private void btnRegisterUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUsersActionPerformed
        btnRegister.setVisible(true);
        lblEmail.setVisible(true);
        lblEmployeeID.setVisible(true);
        lblName.setVisible(true);
        lblPassword.setVisible(true);
        lblRole.setVisible(true);
        txtEmail.setVisible(true);
        txtEmployeeID.setVisible(true);
        txtName.setVisible(true);
        txtPassword.setVisible(true);
        boxRole.setVisible(true);
        btnReturn.setVisible(true);
        
        tblUsers.setVisible(false);
        btnReturn2.setVisible(false);
        jScrollPane2.setVisible(false);
        
        lblDeleteEmployee.setVisible(false);
        btnDelete.setVisible(false);
        txtDeleteEmployeeID.setVisible(false);
        btnReturn3.setVisible(false);
    }//GEN-LAST:event_btnRegisterUsersActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
       btnRegisterUsers.setVisible(true);
        btnDeleteUsers.setVisible(true);
        btnViewUsers.setVisible(true);
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void boxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRoleActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String employeeId = txtEmployeeID.getText().trim();
    String name = txtName.getText().trim();
    String role = (String) boxRole.getSelectedItem();
    String email = txtEmail.getText().trim();
    String password = txtPassword.getText().trim();

    if (employeeId.isEmpty() || name.isEmpty() || role.isEmpty() || email.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    // Define the path to your Employee file
    java.io.File file = new java.io.File("data/Employee.txt");

    try {
        // Check if employee ID or email already exists
        if (file.exists()) {
            java.util.Scanner scanner = new java.util.Scanner(file);
            while (scanner.hasNextLine()) {
                String[] parts = scanner.nextLine().split(",");
                if (parts.length >= 5 && (parts[0].equals(employeeId) || parts[3].equalsIgnoreCase(email))) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Employee ID or Email already exists.");
                    scanner.close();
                    return;
                }
            }
            scanner.close();
        }

        // Append the new user
        java.io.FileWriter writer = new java.io.FileWriter(file, true);
        writer.write(employeeId + "," + name + "," + role + "," + email + "," + password + "\n");
        writer.close();

        javax.swing.JOptionPane.showMessageDialog(this, "User registered successfully!");

        // Clear fields
        txtEmployeeID.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        boxRole.setSelectedIndex(0);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        btnRegister.setVisible(false);
        lblEmail.setVisible(false);
        lblEmployeeID.setVisible(false);
        lblName.setVisible(false);
        lblPassword.setVisible(false);
        lblRole.setVisible(false);
        txtEmail.setVisible(false);
        txtEmployeeID.setVisible(false);
        txtName.setVisible(false);
        txtPassword.setVisible(false);
        boxRole.setVisible(false);
        btnReturn.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUsersActionPerformed
         tblUsers.setVisible(true);
         btnReturn2.setVisible(true);
         jScrollPane2.setVisible(true);


    // Define column names
    String[] columnNames = { "Employee ID", "Name", "Role", "Email", "Password" };
    
    // List to hold rows
    List<String[]> rowData = new ArrayList<>();
    
    // Read the user data file
    try (BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\Lee Anwen\\OneDrive - Asia Pacific University\\Documents\\NetBeansProjects\\OODJ-OWSB\\src\\main\\java\\data\\Employee.txt"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(","); // Adjust delimiter if needed
            if (data.length == 5) {
                rowData.add(data);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading user data file.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create table model from data
    String[][] dataArr = rowData.toArray(new String[0][]);
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(dataArr, columnNames);
    tblUsers.setModel(model);
    btnReturn2.setVisible(true);
    
     btnRegister.setVisible(false);
        lblEmail.setVisible(false);
        lblEmployeeID.setVisible(false);
        lblName.setVisible(false);
        lblPassword.setVisible(false);
        lblRole.setVisible(false);
        txtEmail.setVisible(false);
        txtEmployeeID.setVisible(false);
        txtName.setVisible(false);
        txtPassword.setVisible(false);
        boxRole.setVisible(false);
        btnReturn.setVisible(false);
        
        lblDeleteEmployee.setVisible(false);
        btnDelete.setVisible(false);
        txtDeleteEmployeeID.setVisible(false);
        btnReturn3.setVisible(false);
    }//GEN-LAST:event_btnViewUsersActionPerformed

    private void btnReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn2ActionPerformed
        tblUsers.setVisible(false);
        btnReturn2.setVisible(false);
        jScrollPane2.setVisible(false);

    }//GEN-LAST:event_btnReturn2ActionPerformed

    private void btnReturn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn3ActionPerformed
        lblDeleteEmployee.setVisible(false);
        btnDelete.setVisible(false);
        txtDeleteEmployeeID.setVisible(false);
        btnReturn3.setVisible(false);
    }//GEN-LAST:event_btnReturn3ActionPerformed

    private void btnDeleteUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUsersActionPerformed
        lblDeleteEmployee.setVisible(true);
        btnDelete.setVisible(true);
        txtDeleteEmployeeID.setVisible(true);
        btnReturn3.setVisible(true);
        
        btnRegister.setVisible(false);
        lblEmail.setVisible(false);
        lblEmployeeID.setVisible(false);
        lblName.setVisible(false);
        lblPassword.setVisible(false);
        lblRole.setVisible(false);
        txtEmail.setVisible(false);
        txtEmployeeID.setVisible(false);
        txtName.setVisible(false);
        txtPassword.setVisible(false);
        boxRole.setVisible(false);
        btnReturn.setVisible(false);
        
         tblUsers.setVisible(false);
        btnReturn2.setVisible(false);
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_btnDeleteUsersActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String empIDToDelete = txtDeleteEmployeeID.getText().trim();

    if (empIDToDelete.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter an Employee ID.");
        return;
    }

    File file = new File("C:\\Users\\Lee Anwen\\OneDrive - Asia Pacific University\\Documents\\NetBeansProjects\\OODJ-OWSB\\src\\main\\java\\data\\Employee.txt");
    List<String> updatedUsers = new ArrayList<>();
    boolean found = false;

    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length > 0 && data[0].equals(empIDToDelete)) {
                found = true; // Skip this user
            } else {
                updatedUsers.add(line);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading the file.");
        return;
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "Employee ID not found.");
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
        for (String user : updatedUsers) {
            writer.write(user);
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error writing to the file.");
        return;
    }

    JOptionPane.showMessageDialog(this, "User deleted successfully.");
    txtDeleteEmployeeID.setText(""); // Clear the input field

    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelWelcome;
    private javax.swing.JComboBox<String> boxRole;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteUsers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageItems;
    private javax.swing.JButton btnManageSupplier;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterUsers;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturn2;
    private javax.swing.JButton btnReturn3;
    private javax.swing.JButton btnViewEditPO;
    private javax.swing.JButton btnViewEditPR;
    private javax.swing.JButton btnViewUsers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDeleteEmployee;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtDeleteEmployeeID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
